import axios from 'axios'
const http = axios.create({ baseURL: '/api', timeout: 12000 })
http.interceptors.response.use(r => r.data, e => Promise.reject(e))
// 管理写操作需 admin token + license header
function adminHeaders(){
  return { 'X-Admin-Token': localStorage.getItem('qh_admin_token')||'', 'X-License': localStorage.getItem('qh_key')||'', 'X-Op-Token': localStorage.getItem('qh_op_token')||'' }
}
export const api = {
  verify: (license_key) => http.post('/auth/verify', { license_key }),
  engineState: () => http.get('/engine/state'),
  legs: () => http.get('/engine/legs'),
  alerts: (limit=30) => http.get('/engine/alerts', { params:{limit} }),
  deals: (user, limit=100) => http.get(`/deals/${user}`, { params:{limit} }),
  params: (user) => http.get(`/params/${user}`),
  paramsSave: (row) => http.post('/params/save', { ...row, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  syncLast: () => http.get('/sync/last'),
  sync: (user, days=1) => http.post(`/bridge/sync/${user}?days=${days}`),
  // ── P0 内购/权益 ──
  iapCatalog: () => http.get('/iap/catalog'),
  iapFeatures: () => http.get('/iap/features'),
  iapSaveFeature: (f) => http.post('/admin/iap/feature', { ...f, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  iapDelFeature: (key) => http.post('/admin/iap/feature_del', { key, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  iapSaveProduct: (p) => http.post('/admin/iap/product', { ...p, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  iapDelProduct: (key) => http.post('/admin/iap/product_del', { key, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  iapSaveCategory: (c) => http.post('/admin/iap/category', { ...c, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  entitlements: (user) => http.get(`/entitlements/${user}`),
  grant: (g) => http.post('/admin/entitlement/grant', { ...g, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── P2 三级代理 ──
  agents: () => http.get('/admin/agents'),
  agentSave: (a) => http.post('/admin/agent/save', { ...a, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  agentBind: (b) => http.post('/admin/agent/bind', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  commissions: (agent_code='', settled='') => http.get('/admin/commissions', { params:{ agent_code, settled } }),
  commissionSettle: (agent_code) => http.post('/admin/commission/settle', { agent_code, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── P3 试用 + BI ──
  trialGrant: (g) => http.post('/admin/trial/grant', { ...g, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  trials: () => http.get('/admin/trials'),
  biSymbols: (days=30) => http.get('/admin/bi/symbols', { params:{ days } }),
  biSymbolUsers: (symbol, days=30) => http.get('/admin/bi/symbol_users', { params:{ symbol, days } }),
  biArbStats: (days=30) => http.get('/admin/bi/arb_stats', { params:{ days } }),
  biOverview: (days=30) => http.get('/admin/bi/overview', { params:{ days } }),
  orders: (days=90, product='', username='') => http.get('/admin/orders', { params:{ days, product, username } }),
  ordersFilter: (params) => http.get('/admin/orders', { params }),
  orderReconcile: (b) => http.post('/admin/order/reconcile', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  orderReconcileBatch: (b) => http.post('/admin/order/reconcile_batch', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  reconcileDaily: (days=30) => http.get('/admin/reconcile/daily', { params:{ days }, headers: adminHeaders() }),
  revenue: (days=30) => http.get('/admin/revenue', { params:{ days } }),
  // ── P4a 用户管理 ──
  adminUsers: (q='') => http.get('/admin/users', { params:{ q } }),
  // 导出 xlsx: 带鉴权头以 blob 拉取(响应拦截器返回 r.data, 这里即 Blob)
  usersExport: (q='') => http.get('/admin/users/export', { params:{ q }, responseType:'blob', headers: adminHeaders() }),
  usersGeoStats: () => http.get('/admin/users/geo_stats'),
  adminUser: (u) => http.get(`/admin/user/${u}`),
  userOp: (body) => http.post('/admin/user/op', { ...body, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── P4b 系统 + 总控 ──
  system: () => http.get('/admin/system'),
  pairscan: (hours=24) => http.get('/admin/pairscan', { params:{ hours }, headers: adminHeaders() }),
  // ── 官网管理(site_config + 草稿/发布/回滚) ──
  siteGet: (site='qh') => http.get('/site/config', { params:{ site } }),
  siteSave: (site, cfg) => http.post('/admin/site/save', { site, cfg, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  siteDraftGet: (site='qhwww') => http.get('/admin/site/draft', { params:{ site }, headers: adminHeaders() }),
  siteDraftSave: (site, cfg) => http.post('/admin/site/draft', { site, cfg, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  sitePublish: (site, cfg=null) => http.post('/admin/site/publish', { site, cfg: cfg||{}, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  siteVersions: (site='qhwww') => http.get('/admin/site/versions', { params:{ site }, headers: adminHeaders() }),
  siteRollback: (site, version_id) => http.post('/admin/site/rollback', { site, version_id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  estop: () => http.post('/admin/system/estop', { confirm:true, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  estopClear: () => http.post('/admin/system/estop_clear', { license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  auditLog: (limit=100, action='') => http.get('/admin/audit', { params:{ limit, action } }),
  // ── P5 操作员体系 ──
  opLogin: (username, password) => http.post('/op/login', { username, password }),
  opLogout: () => http.post('/op/logout', {}, { headers: { 'X-Op-Token': localStorage.getItem('qh_op_token')||'' } }),
  opMe: () => http.get('/op/me', { headers: { 'X-Op-Token': localStorage.getItem('qh_op_token')||'' } }),
  operators: () => http.get('/admin/operators', { headers: adminHeaders() }),
  operatorSave: (o) => http.post('/admin/operator/save', { ...o, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  operatorResetPwd: (username, password) => http.post('/admin/operator/reset_password', { username, password, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  resetAdminToken: (new_token='') => http.post('/admin/reset_admin_token', { new_token, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  payConfigGet: () => http.get('/admin/pay/config', { headers: adminHeaders() }),
  payConfigSave: (c) => http.post('/admin/pay/config', { ...c, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  operatorAudit: (limit=100) => http.get('/admin/operator_audit', { params:{ limit }, headers: adminHeaders() }),
  roleSave: (r) => http.post('/admin/role/save', { ...r, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  roleDel: (role) => http.post('/admin/role/del', { role, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── P6 线索中台 + AI客服 ──
  leads: (status='', channel='') => http.get('/admin/leads', { params:{ status, channel } }),
  lead: (id) => http.get(`/admin/lead/${id}`),
  leadReply: (b) => http.post('/admin/lead/reply', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  leadConvert: (b) => http.post('/admin/lead/convert', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  leadAssign: (b) => http.post('/admin/lead/assign', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  leadSetStatus: (b) => http.post('/admin/lead/set_status', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  leadNote: (b) => http.post('/admin/lead/note', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  channels: () => http.get('/admin/channels'),
  channelStatus: () => http.get('/admin/channel/token_status', { headers: adminHeaders() }),
  channelConfig: (c) => http.post('/admin/channel/config', { ...c, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  chatConfig: (site='qh') => http.get('/chat/config', { params:{ site } }),
  chatConfigSave: (c) => http.post('/admin/chat/config', { ...c, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── AI 客服 LLM 服务(复刻 coinadmin ai-support, 跨 site 管理) ──
  aiConfig: (site='qh') => http.get('/admin/ai/config', { params:{ site }, headers: adminHeaders() }),
  aiConfigSave: (c) => http.post('/admin/ai/config', { ...c, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  aiStats: (site='') => http.get('/admin/ai/stats', { params:{ site }, headers: adminHeaders() }),
  aiConversations: (site='', limit=50) => http.get('/admin/ai/conversations', { params:{ site, limit }, headers: adminHeaders() }),
  aiConvMessages: (cid) => http.get(`/admin/ai/conversation/${cid}/messages`, { headers: adminHeaders() }),
  aiChat: (body) => http.post('/ai/chat', body, { timeout: 60000 }),
  // ── P2-5 系统通知 ──
  notifyFeishuStatus: () => http.get('/admin/notify/feishu_status', { headers: adminHeaders() }),
  notifyFeishuTest: (recipient) => http.post('/admin/notify/feishu_test', { recipient, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyEmailGet: () => http.get('/admin/notify/email_config', { headers: adminHeaders() }),
  notifyEmailSave: (c) => http.post('/admin/notify/email_config', { ...c, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyEmailTest: () => http.post('/admin/notify/email_test', { license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyTemplates: () => http.get('/admin/notify/templates', { headers: adminHeaders() }),
  notifyTemplateSave: (t) => http.post('/admin/notify/template', { ...t, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyTemplateDel: (id) => http.post('/admin/notify/template_del', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyBroadcast: (b) => http.post('/admin/notify/broadcast', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyLogs: (channel='', status='', limit=100) => http.get('/admin/notify/logs', { params:{ channel, status, limit }, headers: adminHeaders() }),
  notifySounds: () => http.get('/admin/notify/sounds', { headers: adminHeaders() }),
  notifySoundSave: (s) => http.post('/admin/notify/sound', { ...s, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifySoundDel: (key) => http.post('/admin/notify/sound_del', { key, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  notifyEdgeVoices: (locale='zh-CN') => http.get('/admin/notify/edge_voices', { params:{ locale }, headers: adminHeaders() }),
  notifyTtsUrl: (key, text='') => `/api/notify/tts?key=${encodeURIComponent(key)}${text?('&text='+encodeURIComponent(text)):''}`,
  // ── P3 数据管理 ──
  dmVersion: () => http.get('/admin/datamgr/version', { headers: adminHeaders() }),
  dmDbStats: () => http.get('/admin/datamgr/db/stats', { headers: adminHeaders() }),
  dmDbTables: () => http.get('/admin/datamgr/db/tables', { headers: adminHeaders() }),
  dmDbTable: (name) => http.get(`/admin/datamgr/db/table/${name}`, { headers: adminHeaders() }),
  dmDbBackup: () => http.post('/admin/datamgr/db/backup', { confirm:true, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  dmDbCleanup: () => http.post('/admin/datamgr/db/cleanup', { confirm:true, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  dmSslList: () => http.get('/admin/datamgr/ssl', { headers: adminHeaders() }),
  dmSslUpload: (b) => http.post('/admin/datamgr/ssl/upload', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  dmSslScan: () => http.post('/admin/datamgr/ssl/scan', { license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  dmSslDeploy: (id) => http.post('/admin/datamgr/ssl/deploy', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  dmSslDelete: (id) => http.post('/admin/datamgr/ssl/delete', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  dmWsStats: () => http.get('/admin/datamgr/ws_stats', { headers: adminHeaders() }),
  dmGitPush: (message) => http.post('/admin/datamgr/git-push', { message }, { headers: adminHeaders(), timeout: 240000 }),
  // ── Api2Trade 订阅配置(系统管理) ──
  a2tConfigs: () => http.get('/admin/api2trade/config', { headers: adminHeaders() }),
  a2tSave: (b) => http.post('/admin/api2trade/config/save', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  a2tDelete: (id) => http.post('/admin/api2trade/config/delete', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  a2tTest: (id) => http.post('/admin/api2trade/test', { id }, { headers: adminHeaders(), timeout: 40000 }),
  a2tAccounts: (id=0) => http.get('/admin/api2trade/accounts', { params:{ id }, headers: adminHeaders() }),
  a2tCanary: (b) => http.post('/admin/api2trade/canary', b, { headers: adminHeaders(), timeout: 60000 }),
  // ── 用户账户管理 ──
  a2tBrokers: () => http.get('/admin/a2t/brokers', { headers: adminHeaders(), timeout: 90000 }),
  adminAccounts: (q='') => http.get('/admin/accounts', { params:{ q }, headers: adminHeaders() }),
  adminAcctSave: (b) => http.post('/admin/accounts/save', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  adminAcctDelete: (id) => http.post('/admin/accounts/delete', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  adminAcctPurge: (id) => http.post('/admin/accounts/purge', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── 第一阶段: 会员与积分 + 员工推广 ──
  members: (q='') => http.get('/admin/members', { params:{ q }, headers: adminHeaders() }),
  pointsLedger: (username='', limit=100) => http.get('/admin/points/ledger', { params:{ username, limit }, headers: adminHeaders() }),
  pointsAdjust: (b) => http.post('/admin/points/adjust', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  staffList: () => http.get('/admin/staff', { headers: adminHeaders() }),
  staffSave: (s) => http.post('/admin/staff', { ...s, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  staffDel: (code) => http.post('/admin/staff/del', { code, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  staffStats: () => http.get('/admin/staff/stats', { headers: adminHeaders() }),
  // ── 第二阶段: 折扣券 ──
  coupons: () => http.get('/admin/coupons', { headers: adminHeaders() }),
  couponSave: (b) => http.post('/admin/coupon', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  couponDel: (code) => http.post('/admin/coupon/del', { code, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  couponRedemptions: (code='', limit=100) => http.get('/admin/coupon/redemptions', { params:{ code, limit }, headers: adminHeaders() }),
  // ── 第三阶段: 绩效积分 + 全渠道总看板 ──
  staffPerfAdjust: (b) => http.post('/admin/staff/perf_adjust', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  staffPerfLedger: (staff_code='', limit=100) => http.get('/admin/staff/perf_ledger', { params:{ staff_code, limit }, headers: adminHeaders() }),
  overviewChannels: (days=30) => http.get('/admin/overview/channels', { params:{ days }, headers: adminHeaders() }),
  // ── 活动引擎 ──
  campaigns: () => http.get('/admin/campaigns', { headers: adminHeaders() }),
  campaignMeta: () => http.get('/admin/campaign/meta', { headers: adminHeaders() }),
  campaignSave: (b) => http.post('/admin/campaign', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  campaignDel: (id) => http.post('/admin/campaign/del', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  campaignGrants: (campaign_id=0, limit=100) => http.get('/admin/campaign/grants', { params:{ campaign_id, limit }, headers: adminHeaders() }),
  recallCfgGet: () => http.get('/admin/recall/config', { headers: adminHeaders() }),
  recallCfgSave: (b) => http.post('/admin/recall/config', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  staffPerfCfgGet: () => http.get('/admin/staff_perf/config', { headers: adminHeaders() }),
  staffPerfCfgSave: (b) => http.post('/admin/staff_perf/config', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  // ── 周期冲榜赛 ──
  contests: () => http.get('/admin/contests', { headers: adminHeaders() }),
  contestSave: (b) => http.post('/admin/contest', { ...b, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  contestDel: (id) => http.post('/admin/contest/del', { id, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  contestSettle: (id, force=false) => http.post('/admin/contest/settle', { id, force, license_key: localStorage.getItem('qh_key')||'' }, { headers: adminHeaders() }),
  contestResults: (contest_id, period_key='') => http.get('/admin/contest/results', { params:{ contest_id, period_key }, headers: adminHeaders() }),
  contestPreview: (kind, metric, period) => http.get('/admin/contest/preview', { params:{ kind, metric, period }, headers: adminHeaders() }),
}







