"""Initial schema

Revision ID: 8d7a09906f40
Revises: 
Create Date: 2026-02-18 15:00:23.635335+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7a09906f40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('platform_name', sa.String(length=20), nullable=False),
    sa.Column('api_base_url', sa.String(length=100), nullable=False),
    sa.Column('ws_base_url', sa.String(length=100), nullable=False),
    sa.Column('account_api_type', sa.String(length=30), nullable=False),
    sa.Column('market_api_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('platform_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.SmallInteger(), nullable=False),
    sa.Column('account_name', sa.String(length=50), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=False),
    sa.Column('api_secret', sa.String(length=256), nullable=False),
    sa.Column('passphrase', sa.String(length=100), nullable=True),
    sa.Column('mt5_id', sa.String(length=100), nullable=True),
    sa.Column('mt5_server', sa.String(length=100), nullable=True),
    sa.Column('mt5_primary_pwd', sa.String(length=256), nullable=True),
    sa.Column('is_mt5_account', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.platform_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('arbitrage_tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('open_spread', sa.Float(), nullable=False),
    sa.Column('close_spread', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('open_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('close_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_arbitrage_tasks_user_id'), 'arbitrage_tasks', ['user_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_level', sa.String(length=10), nullable=False),
    sa.Column('alert_message', sa.String(length=200), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('expire_time', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_risk_alerts_user_id'), 'risk_alerts', ['user_id'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('target_spread', sa.Float(), nullable=False),
    sa.Column('order_qty', sa.Float(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('mt5_stuck_threshold', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_strategy_configs_user_id'), 'strategy_configs', ['user_id'], unique=False)
    op.create_table('order_records',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('filled_qty', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('platform_order_id', sa.String(length=100), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_records_account_id'), 'order_records', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_records_account_id'), table_name='order_records')
    op.drop_table('order_records')
    op.drop_index(op.f('ix_strategy_configs_user_id'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_risk_alerts_user_id'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_arbitrage_tasks_user_id'), table_name='arbitrage_tasks')
    op.drop_table('arbitrage_tasks')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('platforms')
    # ### end Alembic commands ###
