// S3(coin 借币点差)规则元数据 —— 1:1 对齐 coin RulesPage 中文分组;主控台弹层与规则中心共用
export const S3_META = {
  auto_push_spread: { label: '自动推送点差', w: 56, tip: '点差≥此值自动推送进候选' },
  confirm_delay_sec: { label: '推送二次确认', suffix: '秒', w: 40 },
  confirm_skip_spread: { label: '点差≥直推(免确认)', w: 56 },
  interest_filter: { label: '日利息拦截', suffix: '%', w: 48, tip: '日利率高于此值的币不进候选' },
  remove_spread: { label: '点差不足移除', w: 56 },
  removed_cooldown_minutes: { label: '移除后冷却', suffix: '分', w: 40 },
  spread_stale_sec: { label: '点差过期', suffix: '秒', w: 48 },
  borrow_spread: { label: '挂单点差', w: 56 },
  open_spread: { label: '开仓点差', w: 56 },
  open_spread_buffer: { label: '开仓点差缓冲', w: 56 },
  order_amount: { label: '单笔下单额', suffix: 'U', w: 56 },
  borrow_delay_sec: { label: '借币延迟开仓', suffix: '秒', w: 40 },
  stabilize_sec: { label: '点差稳定期', suffix: '秒', w: 48 },
  slippage_pct: { label: '滑点保护', suffix: '%', w: 48 },
  follow_type: { label: '跟单方式', type: 'select', options: ['market', 'limit'] },
  tier_ratios: { label: '阶梯比例', w: 90, tip: '逗号分隔;空=不分层' },
  max_spread_pct: { label: '最大点差', suffix: '%', w: 48 },
  min_volume_24h: { label: '24h最小成交额·现货', w: 72 },
  min_volume_24h_futures: { label: '24h最小成交额·合约', w: 72 },
  filter_duration_ms: { label: '过滤持续', suffix: 'ms', w: 48 },
  min_borrow_usdt: { label: '最小借币额', suffix: 'U', w: 56 },
  block_risky_open: { label: '风险开仓拦截', type: 'bool' },
  close_spread: { label: '平仓点差', w: 56 },
  close_funding_ratio: { label: '平仓:资息倍率<', w: 48 },
  repay_funding_ratio: { label: '还币:资息倍率<', w: 48 },
  repay_ban_minutes: { label: '首借后禁自动还币', suffix: '分', w: 40 },
  borrow_rate_per_sec: { label: '借币速率', suffix: '/秒', w: 40 },
  borrow_via_otoco: { label: 'OTOCO 借币', type: 'bool', tip: 'OTOCO=1500 权重独立预算' },
  otoco_legs: { label: 'OTOCO 腿数', type: 'select', options: ['1', '2', '3'] },
  borrow_mode: { label: '借币方式', type: 'select', options: ['repay', 'otoco', 'single', 'multi'], tip: 'repay/otoco/single/multi 四模式' },
  borrow_venues: { label: '借币 venue', type: 'venues', options: ['binance', 'okx', 'gate', 'bybit', 'bitget'], tip: '点击排序=优先级顺序' },
  multi_max_accounts_per_symbol: { label: '单币最多账户', w: 32 },
  collateral_ratio: { label: '质押率', w: 48 },
  hedge_via_master: { label: '主账户对冲', type: 'bool', tip: 'hedge_via_master:合约对冲腿走主账户' },
  hedge_auto_converge: { label: '对冲自动收敛', type: 'bool' },
  max_loss_per_position: { label: '单仓最大亏损', suffix: 'U', w: 56, tip: 'None=不启用' },
  taker_fee_spot: { label: '现货 taker 费率', w: 72 },
  taker_fee_futures: { label: '合约 taker 费率', w: 72 },
  bnb_burn_enabled: { label: 'BNB 抵扣手续费', type: 'bool' },
}
export const S3_GROUPS = [
  { title: '推送 / 候选', keys: ['auto_push_spread', 'confirm_delay_sec', 'confirm_skip_spread', 'interest_filter', 'remove_spread', 'removed_cooldown_minutes', 'spread_stale_sec'] },
  { title: '开仓', keys: ['borrow_spread', 'open_spread', 'open_spread_buffer', 'order_amount', 'borrow_delay_sec', 'stabilize_sec', 'slippage_pct', 'follow_type', 'tier_ratios', 'max_spread_pct', 'min_volume_24h', 'min_volume_24h_futures', 'filter_duration_ms', 'min_borrow_usdt', 'block_risky_open'] },
  { title: '平仓 / 还币', keys: ['close_spread', 'close_funding_ratio', 'repay_funding_ratio', 'repay_ban_minutes'] },
  { title: '借币执行', keys: ['borrow_rate_per_sec', 'borrow_via_otoco', 'otoco_legs', 'borrow_mode', 'borrow_venues', 'multi_max_accounts_per_symbol', 'collateral_ratio'] },
  { title: '对冲 / 风控 / 费率', keys: ['hedge_via_master', 'hedge_auto_converge', 'max_loss_per_position', 'taker_fee_spot', 'taker_fee_futures', 'bnb_burn_enabled'] },
]

